#!/usr/bin/env bash
# ============================================================================
#  setup.sh - All-in-one installer & manager for the Aurora Telegram
#             Downloader Bot (SoundCloud / Spotify / YouTube / Pinterest /
#             Instagram / TikTok / Twitter)
#
#  Tested on:  Ubuntu 20.04 / 22.04 / 24.04  (also works on Debian 11+)
#
#  Features:
#    * Full system + Python dependency installation (ffmpeg, venv, pip, ...)
#    * Virtualenv creation + requirements.txt install
#    * Interactive bot configuration (token, channel, port, cookies)
#    * systemd service setup (system OR user level, with auto-restart)
#    * Log rotation, health checks, backup / restore database
#    * Update (git pull + deps + restart), status, logs, reconfigure, remove
#
#  Usage:
#    ./setup.sh                # interactive menu
#    ./setup.sh --install      # first-time install
#    ./setup.sh --restart
#    ./setup.sh --logs
#    ./setup.sh --help
# ============================================================================
set -euo pipefail

# ----------------------------------------------------------------------------
#  Colors (using $'...' so they contain real escape chars - works in heredocs)
# ----------------------------------------------------------------------------
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'
CYAN=$'\033[0;36m'; MAGENTA=$'\033[0;35m'; BOLD=$'\033[1m'; NC=$'\033[0m'

# ----------------------------------------------------------------------------
#  Paths & defaults
# ----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${SCRIPT_DIR}"
VENV_DIR="${PROJECT_DIR}/venv"
ENV_FILE="${PROJECT_DIR}/.env"
CONFIG_FILE="${PROJECT_DIR}/.setup-config"
LOG_DIR="${PROJECT_DIR}/logs"
BACKUP_DIR="${PROJECT_DIR}/backups"
BOT_SCRIPT="${BOT_SCRIPT:-aurora_bot.py}"
BOT_SCRIPT_ABS="${PROJECT_DIR}/${BOT_SCRIPT}"
DB_PATH="${PROJECT_DIR}/aurora.db"
COOKIES_PATH="${PROJECT_DIR}/cookies.txt"

# Service defaults (overridden by config / prompts)
SERVICE_NAME="${SERVICE_NAME:-tg-downloader-bot}"
USER_SERVICE="${USER_SERVICE:-false}"
RUN_USER="${RUN_USER:-${USER:-$(whoami)}}"
RESTART="${RESTART:-always}"
BOT_PORT="${BOT_PORT:-5000}"

# Load saved configuration if it exists
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
fi

# Determine systemctl command prefix
if [[ "$USER_SERVICE" == "true" ]]; then
    SYSTEMCTL="systemctl --user"
    SERVICE_DIR="${HOME}/.config/systemd/user"
    INSTALL_TARGET="default.target"
else
    SYSTEMCTL="sudo systemctl"
    SERVICE_DIR="/etc/systemd/system"
    INSTALL_TARGET="multi-user.target"
fi
SERVICE_FILE="${SERVICE_DIR}/${SERVICE_NAME}.service"

# ----------------------------------------------------------------------------
#  Helpers
# ----------------------------------------------------------------------------
log()  { echo -e "${GREEN}[$(date +%H:%M:%S)]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*" >&2; }
ok()   { echo -e "${GREEN}[✓]${NC} $*"; }
info() { echo -e "${CYAN}[i]${NC} $*"; }

press_enter() {
    echo ""
    read -rp "$(echo -e ${BOLD}"Press Enter to continue..."${NC})"
}

check_systemd() {
    if ! pidof systemd &>/dev/null; then
        warn "systemd not running - service management unavailable."
        return 1
    fi
    return 0
}

save_config() {
    cat > "$CONFIG_FILE" <<EOF
# Auto-generated by setup.sh - do not edit by hand (use ./setup.sh --reconfigure)
SERVICE_NAME="${SERVICE_NAME}"
USER_SERVICE="${USER_SERVICE}"
BOT_SCRIPT="${BOT_SCRIPT}"
RUN_USER="${RUN_USER}"
RESTART="${RESTART}"
BOT_PORT="${BOT_PORT}"
EOF
    ok "Configuration saved to ${CONFIG_FILE}"
}

# Patch a Python assignment inside the bot file: KEY = "old" -> KEY = "new"
# Usage: patch_bot_value BOT_TOKEN "new_value"
patch_bot_value() {
    local key="$1" val="$2"
    # Escape special chars for sed replacement
    local esc_val
    esc_val=$(printf '%s\n' "$val" | sed -e 's/[\/&|]/\\&/g')
    if grep -q "^${key}[[:space:]]*=" "$BOT_SCRIPT_ABS"; then
        sed -i -E "s|^${key}[[:space:]]*=.*|${key} = \"${esc_val}\"|" "$BOT_SCRIPT_ABS"
        return 0
    fi
    return 1
}

# ----------------------------------------------------------------------------
#  Action: install
# ----------------------------------------------------------------------------
do_install() {
    echo -e "${CYAN}${BOLD}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║   Aurora Telegram Downloader Bot (aiogram 3.x) - Install   ║"
    echo "║   SoundCloud | Spotify | YouTube | Pinterest | Instagram    ║"
    echo "║   TikTok | Twitter (X)                                       ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"

    # --- 1. Pre-flight: must be run from the project dir ---
    if [[ ! -f "$BOT_SCRIPT_ABS" ]]; then
        err "Bot script '${BOT_SCRIPT}' not found in ${PROJECT_DIR}"
        err "Run this script from the project root directory."
        return 1
    fi

    # --- 2. OS package updates + system deps ---
    info "Updating apt cache and installing system dependencies..."
    sudo apt-get update -qq
    sudo apt-get install -y -qq \
        python3 python3-venv python3-pip python3-dev \
        ffmpeg \
        git curl wget \
        ca-certificates \
        build-essential 2>/dev/null

    # Python version check
    if [ "$(python3 -c 'import sys; print(sys.version_info >= (3,9))')" != "True" ]; then
        err "Python 3.9+ required."
        return 1
    fi
    ok "Python $(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")') OK"

    # ffmpeg check
    if ! command -v ffmpeg &>/dev/null; then
        err "ffmpeg could not be installed. yt-dlp needs it for audio conversion."
        return 1
    fi
    ok "ffmpeg $(ffmpeg -version 2>/dev/null | head -1 | awk '{print $3}') OK"

    # --- 3. Gather configuration ---
    echo -e "\n${CYAN}${BOLD}📝  Bot Configuration${NC}"
    echo -e "    (Get your token from @BotFather in Telegram)\n"

    read -rsp "  Bot Token: " BOT_TOKEN
    echo ""
    if [[ -z "$BOT_TOKEN" ]]; then
        err "Bot token is required."
        return 1
    fi

    read -rp "  Forced channel username (with @, leave blank to skip): " CHANNEL_USERNAME
    read -rp "  Companion channel (with @, leave blank to skip): " COMPANION_ID_INPUT
    read -rp "  aiohttp keep-alive port [${BOT_PORT}]: " PORT_INPUT
    BOT_PORT="${PORT_INPUT:-$BOT_PORT}"

    # Cookies (optional but helps YouTube)
    echo -e "\n${CYAN}🍪  YouTube cookies (optional, helps bypass bot-detection)${NC}"
    read -rp "  Path to cookies.txt (leave blank to skip): " COOKIES_INPUT
    if [[ -n "$COOKIES_INPUT" && -f "$COOKIES_INPUT" ]]; then
        cp "$COOKIES_INPUT" "$COOKIES_PATH"
        ok "cookies.txt copied to project dir"
    elif [[ -n "$COOKIES_INPUT" ]]; then
        warn "File not found: ${COOKIES_INPUT} - skipping cookies setup"
    fi

    # --- 4. Patch bot file with the new config ---
    info "Patching ${BOT_SCRIPT} with your configuration..."
    cp "$BOT_SCRIPT_ABS" "${BOT_SCRIPT_ABS}.bak.$(date +%s)"
    patch_bot_value "BOT_TOKEN" "$BOT_TOKEN" || warn "BOT_TOKEN not patched (key not found)"
    if [[ -n "$CHANNEL_USERNAME" ]]; then
        patch_bot_value "CHANNEL_USERNAME" "$CHANNEL_USERNAME" || true
    fi
    if [[ -n "$COMPANION_ID_INPUT" ]]; then
        patch_bot_value "COMPANION_ID" "$COMPANION_ID_INPUT" || true
    fi
    patch_bot_value "PORT" "int(os.environ.get('PORT', ${BOT_PORT}))" || true
    ok "Bot configured"

    # --- 5. Write .env (for reference + systemd EnvironmentFile) ---
    cat > "$ENV_FILE" <<EOF
# Reference environment file - the bot reads its config from aurora_bot.py
# This file is used by the systemd service for any extra env vars.
BOT_PORT=${BOT_PORT}
EOF
    ok ".env created"

    # --- 6. Virtual environment + Python deps ---
    if [[ ! -d "$VENV_DIR" ]]; then
        info "Creating Python virtual environment at ${VENV_DIR}..."
        python3 -m venv "$VENV_DIR"
    fi

    PIP="${VENV_DIR}/bin/pip"
    info "Upgrading pip / setuptools / wheel..."
    "$PIP" install --upgrade pip setuptools wheel -q

    if [[ -f "${PROJECT_DIR}/requirements.txt" ]]; then
        info "Installing Python dependencies from requirements.txt..."
        "$PIP" install -r "${PROJECT_DIR}/requirements.txt"
    else
        warn "requirements.txt not found - installing core deps manually..."
        "$PIP" install -q aiogram yt-dlp aiohttp requests Pillow mutagen spotapi
    fi
    ok "Python dependencies installed"

    # --- 7. Pre-flight syntax check ---
    info "Running syntax check on the bot..."
    if "${VENV_DIR}/bin/python" -m py_compile "$BOT_SCRIPT_ABS"; then
        ok "Syntax check passed"
    else
        err "Syntax check failed! Please review ${BOT_SCRIPT}"
        return 1
    fi

    # --- 8. Smoke test: import the module ---
    info "Smoke test: verifying imports..."
    if "${VENV_DIR}/bin/python" -c "
import importlib.util, sys
spec = importlib.util.spec_from_file_location('bot', '${BOT_SCRIPT_ABS}')
m = importlib.util.module_from_spec(spec)
try:
    spec.loader.exec_module(m)
    print('  SPOTAPI_AVAILABLE =', m.SPOTAPI_AVAILABLE)
    print('  Bot username = @' + m.BOT_USERNAME)
    sys.exit(0)
except SystemExit:
    raise
except Exception as e:
    print('  Import warning:', e)
    sys.exit(0)
" >/dev/null 2>&1; then
        ok "Smoke test passed"
    else
        warn "Smoke test had warnings (bot may still work - check logs after start)"
    fi

    # --- 9. systemd service setup ---
    CREATE_SERVICE=false
    if check_systemd; then
        CREATE_SERVICE=true
        echo -e "\n${CYAN}${BOLD}🔧  systemd service setup${NC}"
        read -rp "  Service name [${SERVICE_NAME}]: " sn; SERVICE_NAME="${sn:-$SERVICE_NAME}"
        read -rp "  Run as user [${RUN_USER}]: " ru; RUN_USER="${ru:-$RUN_USER}"
        read -rp "  Restart policy [${RESTART}]: " rp; RESTART="${rp:-$RESTART}"
        read -rp "  Use --user service (no sudo)? [y/N]: " uc
        if [[ "$uc" =~ ^[Yy]$ ]]; then
            USER_SERVICE=true
            SYSTEMCTL="systemctl --user"
            SERVICE_DIR="${HOME}/.config/systemd/user"
            INSTALL_TARGET="default.target"
        else
            USER_SERVICE=false
            SYSTEMCTL="sudo systemctl"
            SERVICE_DIR="/etc/systemd/system"
            INSTALL_TARGET="multi-user.target"
        fi
        SERVICE_FILE="${SERVICE_DIR}/${SERVICE_NAME}.service"
        PYTHON_VENV_ABS="${VENV_DIR}/bin/python"
        mkdir -p "$LOG_DIR"

        # Enable lingering for user services so they survive logout
        if [[ "$USER_SERVICE" == "true" ]]; then
            loginctl enable-linger "$RUN_USER" 2>/dev/null || true
        fi

        info "Writing service file to ${SERVICE_FILE}..."
        cat > "/tmp/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Aurora Telegram Downloader Bot (${SERVICE_NAME})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${RUN_USER}
WorkingDirectory=${PROJECT_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${PYTHON_VENV_ABS} ${BOT_SCRIPT_ABS}
Restart=${RESTART}
RestartSec=10
StandardOutput=append:${LOG_DIR}/bot.log
StandardError=append:${LOG_DIR}/bot_error.log
# Give the bot a generous timeout to start (it boots aiohttp + Telegram polling)
TimeoutStartSec=60
# Resource limits - prevent runaway memory
MemoryMax=1G
CPUQuota=200%

[Install]
WantedBy=${INSTALL_TARGET}
EOF

        if [[ "$USER_SERVICE" == "true" ]]; then
            mkdir -p "$SERVICE_DIR"
            mv "/tmp/${SERVICE_NAME}.service" "$SERVICE_FILE"
            $SYSTEMCTL daemon-reload
            $SYSTEMCTL enable "${SERVICE_NAME}.service"
            $SYSTEMCTL start "${SERVICE_NAME}.service"
        else
            sudo mv "/tmp/${SERVICE_NAME}.service" "$SERVICE_FILE"
            $SYSTEMCTL daemon-reload
            $SYSTEMCTL enable "${SERVICE_NAME}.service"
            $SYSTEMCTL start "${SERVICE_NAME}.service"
        fi
        ok "Service '${SERVICE_NAME}' installed and started"
    else
        warn "Skipping systemd setup - you'll need to run the bot manually."
    fi

    # --- 10. Log rotation ---
    if [[ "$CREATE_SERVICE" == "true" ]] && [[ "$USER_SERVICE" == "false" ]]; then
        info "Configuring logrotate for ${LOG_DIR}..."
        sudo tee /etc/logrotate.d/${SERVICE_NAME} >/dev/null <<EOF
${LOG_DIR}/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
EOF
        ok "Log rotation configured (7 daily rotations)"
    fi

    # --- 11. Save config + final banner ---
    save_config

    echo ""
    echo -e "${GREEN}${BOLD}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║            🎉  Installation completed successfully!          ║"
    echo "╠══════════════════════════════════════════════════════════════╣"
    echo "║  Bot file:    ${BOT_SCRIPT}"
    echo "║  Venv:        venv/"
    echo "║  Logs:        logs/bot.log"
    echo "║  Database:    sc_bot.db (auto-created on first run)"
    if [[ "$CREATE_SERVICE" == "true" ]]; then
        echo "║  Service:     ${SERVICE_NAME} (running)"
    fi
    echo "║  Health:      http://localhost:${BOT_PORT}/health"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    if [[ "$CREATE_SERVICE" != "true" ]]; then
        echo -e "${YELLOW}Run manually:${NC}  source venv/bin/activate && python ${BOT_SCRIPT}"
    else
        echo -e "${CYAN}Next steps:${NC}"
        echo -e "  View logs:    ./setup.sh --logs"
        echo -e "  Check status: ./setup.sh --status"
        echo -e "  Restart:      ./setup.sh --restart"
    fi
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: update (git pull + deps + restart)
# ----------------------------------------------------------------------------
do_update() {
    info "Updating bot code and dependencies..."
    cd "$PROJECT_DIR"
    if [[ -d ".git" ]]; then
        log "Pulling latest code..."
        git pull
        ok "Code updated"
    else
        warn "Not a git repo - skipping git pull"
    fi

    if [[ -f "${PROJECT_DIR}/requirements.txt" ]] && [[ -d "$VENV_DIR" ]]; then
        info "Updating Python dependencies..."
        "${VENV_DIR}/bin/pip" install --upgrade -r "${PROJECT_DIR}/requirements.txt"
        ok "Dependencies updated"
    fi

    # Re-run syntax check
    if [[ -d "$VENV_DIR" ]]; then
        info "Syntax check..."
        if "${VENV_DIR}/bin/python" -m py_compile "$BOT_SCRIPT_ABS"; then
            ok "Syntax OK"
        else
            err "Syntax check failed - NOT restarting the service"
            return 1
        fi
    fi

    if [[ -f "$SERVICE_FILE" ]] && check_systemd; then
        info "Restarting service to apply changes..."
        $SYSTEMCTL restart "${SERVICE_NAME}"
        ok "Service restarted"
    else
        warn "Service not installed - restart the bot manually"
    fi
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: restart
# ----------------------------------------------------------------------------
do_restart() {
    if [[ ! -f "$SERVICE_FILE" ]]; then
        err "Service file not found. Run './setup.sh --install' first."
        press_enter; return 1
    fi
    check_systemd || return 1
    info "Restarting '${SERVICE_NAME}'..."
    $SYSTEMCTL restart "${SERVICE_NAME}"
    ok "Service restarted"
    sleep 2
    $SYSTEMCTL status "${SERVICE_NAME}" --no-pager -l | head -15 || true
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: stop
# ----------------------------------------------------------------------------
do_stop() {
    if [[ ! -f "$SERVICE_FILE" ]]; then
        err "Service file not found."; press_enter; return 1
    fi
    check_systemd || return 1
    info "Stopping '${SERVICE_NAME}'..."
    $SYSTEMCTL stop "${SERVICE_NAME}"
    ok "Service stopped"
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: status
# ----------------------------------------------------------------------------
do_status() {
    if [[ ! -f "$SERVICE_FILE" ]]; then
        err "Service file not found."; press_enter; return 1
    fi
    check_systemd || return 1
    echo -e "${CYAN}────────────── systemd status ──────────────${NC}"
    $SYSTEMCTL status "${SERVICE_NAME}" --no-pager -l || true
    echo ""
    echo -e "${CYAN}────────────── resource usage ──────────────${NC}"
    $SYSTEMCTL show "${SERVICE_NAME}" -p MemoryCurrent -p CPUUsageNSec -p ActiveState -p SubState || true
    echo ""
    echo -e "${CYAN}────────────── last 15 log lines ──────────────${NC}"
    tail -n 15 "${LOG_DIR}/bot.log" 2>/dev/null || warn "No bot.log yet"
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: logs (live follow)
# ----------------------------------------------------------------------------
do_logs() {
    if [[ ! -f "$SERVICE_FILE" ]]; then
        err "Service file not found."; press_enter; return 1
    fi
    check_systemd || return 1
    echo -e "${CYAN}Following logs (Ctrl+C to exit)...${NC}"
    if [[ "$USER_SERVICE" == "true" ]]; then
        journalctl --user -u "${SERVICE_NAME}" -f -n 50
    else
        journalctl -u "${SERVICE_NAME}" -f -n 50
    fi
}

# ----------------------------------------------------------------------------
#  Action: reconfigure (edit bot values + .env)
# ----------------------------------------------------------------------------
do_reconfigure() {
    if [[ ! -f "$BOT_SCRIPT_ABS" ]]; then
        err "Bot script not found."; press_enter; return 1
    fi
    echo -e "${CYAN}${BOLD}📝  Reconfigure bot settings${NC}"
    echo -e "    (Press Enter to keep current value)\n"

    # Read current values
    CUR_TOKEN=$(grep -E "^BOT_TOKEN[[:space:]]*=" "$BOT_SCRIPT_ABS" | head -1 | sed -E 's/.*=["'"'"']([^"'"'"']*)["'"'"'].*/\1/')
    CUR_CHAN=$(grep -E "^CHANNEL_USERNAME[[:space:]]*=" "$BOT_SCRIPT_ABS" | head -1 | sed -E 's/.*=["'"'"']([^"'"'"']*)["'"'"'].*/\1/')
    CUR_PORT=$(grep -E "^PORT[[:space:]]*=" "$BOT_SCRIPT_ABS" | head -1 | grep -oE '[0-9]+' | head -1)

    read -rp "  Bot Token [${CUR_TOKEN:0:15}...]: " NEW_TOKEN
    [[ -n "$NEW_TOKEN" ]] && patch_bot_value "BOT_TOKEN" "$NEW_TOKEN"

    read -rp "  Channel username [${CUR_CHAN}]: " NEW_CHAN
    [[ -n "$NEW_CHAN" ]] && patch_bot_value "CHANNEL_USERNAME" "$NEW_CHAN"

    read -rp "  Port [${CUR_PORT}]: " NEW_PORT
    if [[ -n "$NEW_PORT" ]]; then
        BOT_PORT="$NEW_PORT"
        patch_bot_value "PORT" "int(os.environ.get('PORT', ${NEW_PORT}))"
    fi

    ok "Configuration updated"

    if [[ -f "$SERVICE_FILE" ]] && check_systemd; then
        read -rp "  Restart service now? [Y/n]: " rc
        if [[ ! "$rc" =~ ^[Nn]$ ]]; then
            $SYSTEMCTL restart "${SERVICE_NAME}"
            ok "Service restarted"
        fi
    fi
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: backup database (+ config)
# ----------------------------------------------------------------------------
do_backup() {
    mkdir -p "$BACKUP_DIR"
    local TS; TS=$(date +%Y%m%d_%H%M%S)
    local ARCHIVE="${BACKUP_DIR}/bot_backup_${TS}.tar.gz"
    info "Creating backup..."
    local FILES=()
    [[ -f "$DB_PATH" ]] && FILES+=("$(basename "$DB_PATH")")
    [[ -f "$BOT_SCRIPT_ABS" ]] && FILES+=("$BOT_SCRIPT")
    [[ -f "$ENV_FILE" ]] && FILES+=(".env")
    [[ -f "$CONFIG_FILE" ]] && FILES+=(".setup-config")
    [[ -f "$COOKIES_PATH" ]] && FILES+=("cookies.txt")

    if [[ ${#FILES[@]} -eq 0 ]]; then
        err "Nothing to back up."
        press_enter; return 1
    fi

    tar -czf "$ARCHIVE" -C "$PROJECT_DIR" "${FILES[@]}" 2>/dev/null
    ok "Backup created: ${ARCHIVE}"
    info "Contents: ${FILES[*]}"
    # Keep only the last 10 backups
    ls -1t "${BACKUP_DIR}"/bot_backup_*.tar.gz 2>/dev/null | tail -n +11 | xargs -r rm
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: restore database
# ----------------------------------------------------------------------------
do_restore() {
    if [[ ! -d "$BACKUP_DIR" ]] || [[ -z "$(ls -A "$BACKUP_DIR" 2>/dev/null)" ]]; then
        err "No backups found in ${BACKUP_DIR}"
        press_enter; return 1
    fi
    echo -e "${CYAN}Available backups:${NC}"
    local i=0
    local arr=()
    while IFS= read -r f; do
        i=$((i+1))
        arr+=("$f")
        echo -e "  ${BOLD}${i})${NC} $(basename "$f")  ($(du -h "$f" | cut -f1))"
    done < <(ls -1t "${BACKUP_DIR}"/bot_backup_*.tar.gz 2>/dev/null)

    echo ""
    read -rp "Select backup to restore [1-${i}]: " choice
    if ! [[ "$choice" =~ ^[0-9]+$ ]] || (( choice < 1 || choice > i )); then
        err "Invalid selection"; press_enter; return 1
    fi
    local target="${arr[$((choice-1))]}"

    # Stop service first if running
    local was_running=false
    if [[ -f "$SERVICE_FILE" ]] && $SYSTEMCTL is-active --quiet "${SERVICE_NAME}" 2>/dev/null; then
        was_running=true
        info "Stopping service for restore..."
        $SYSTEMCTL stop "${SERVICE_NAME}" || true
    fi

    info "Restoring from $(basename "$target")..."
    tar -xzf "$target" -C "$PROJECT_DIR"
    ok "Restore complete"

    if $was_running; then
        info "Starting service..."
        $SYSTEMCTL start "${SERVICE_NAME}" || true
        ok "Service started"
    fi
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: health check
# ----------------------------------------------------------------------------
do_health() {
    local port="${BOT_PORT:-5000}"
    info "Checking health endpoint at http://localhost:${port}/health ..."
    if curl -sf --max-time 5 "http://localhost:${port}/health" >/dev/null 2>&1; then
        ok "Health check PASSED - bot is responding"
        curl -s "http://localhost:${port}/health" 2>/dev/null || true
        echo ""
    else
        err "Health check FAILED - bot not responding on port ${port}"
        warn "Check: ./setup.sh --status"
    fi
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: remove service
# ----------------------------------------------------------------------------
do_remove_service() {
    if [[ ! -f "$SERVICE_FILE" ]]; then
        warn "Service file not found - nothing to remove."
        press_enter; return 0
    fi
    check_systemd || return 1
    echo -e "${YELLOW}${BOLD}⚠️  This will remove the '${SERVICE_NAME}' service.${NC}"
    read -rp "Are you sure? [y/N]: " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo "Aborted."; press_enter; return 0
    fi

    info "Removing service '${SERVICE_NAME}'..."
    $SYSTEMCTL stop "${SERVICE_NAME}" 2>/dev/null || true
    $SYSTEMCTL disable "${SERVICE_NAME}" 2>/dev/null || true
    if [[ "$USER_SERVICE" == "true" ]]; then
        rm -f "$SERVICE_FILE"
        $SYSTEMCTL daemon-reload
    else
        sudo rm -f "$SERVICE_FILE"
        sudo rm -f "/etc/logrotate.d/${SERVICE_NAME}" 2>/dev/null || true
        $SYSTEMCTL daemon-reload
    fi
    ok "Service removed"
    rm -f "$CONFIG_FILE"
    warn "Bot files, venv, database and logs were left untouched."
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: full uninstall (service + venv + logs)
# ----------------------------------------------------------------------------
do_full_uninstall() {
    echo -e "${RED}${BOLD}⚠️  DANGER: Full uninstall${NC}"
    echo -e "  This will remove: service, venv, logs, database, backups."
    echo -e "  Bot source files will NOT be deleted.\n"
    read -rp "Type 'YES' to confirm: " confirm
    if [[ "$confirm" != "YES" ]]; then
        echo "Aborted."; press_enter; return 0
    fi

    # Remove service
    if [[ -f "$SERVICE_FILE" ]]; then
        check_systemd && {
            $SYSTEMCTL stop "${SERVICE_NAME}" 2>/dev/null || true
            $SYSTEMCTL disable "${SERVICE_NAME}" 2>/dev/null || true
            if [[ "$USER_SERVICE" == "true" ]]; then
                rm -f "$SERVICE_FILE"
                $SYSTEMCTL daemon-reload
            else
                sudo rm -f "$SERVICE_FILE"
                sudo rm -f "/etc/logrotate.d/${SERVICE_NAME}" 2>/dev/null || true
                $SYSTEMCTL daemon-reload
            fi
        }
    fi

    # Remove venv, logs, db, backups
    [[ -d "$VENV_DIR" ]] && rm -rf "$VENV_DIR" && ok "Removed venv"
    [[ -d "$LOG_DIR" ]] && rm -rf "$LOG_DIR" && ok "Removed logs"
    [[ -f "$DB_PATH" ]] && rm -f "$DB_PATH" && ok "Removed database"
    [[ -d "$BACKUP_DIR" ]] && rm -rf "$BACKUP_DIR" && ok "Removed backups"
    [[ -f "$CONFIG_FILE" ]] && rm -f "$CONFIG_FILE"
    [[ -f "$ENV_FILE" ]] && rm -f "$ENV_FILE"

    ok "Full uninstall complete. Bot source files preserved."
    press_enter
}

# ----------------------------------------------------------------------------
#  Action: show help
# ----------------------------------------------------------------------------
do_help() {
    cat <<EOF
${BOLD}Aurora Telegram Downloader Bot - setup.sh${NC}

${BOLD}Usage:${NC}
  ./setup.sh [OPTION]

${BOLD}Options:${NC}
  ${GREEN}--install${NC}        Full install (system deps + venv + service)
  ${GREEN}--update${NC}         Pull latest code + update deps + restart
  ${GREEN}--restart${NC}        Restart the bot service
  ${GREEN}--stop${NC}           Stop the bot service
  ${GREEN}--status${NC}         Show service status + resource usage + recent logs
  ${GREEN}--logs${NC}           Follow live logs (Ctrl+C to exit)
  ${GREEN}--reconfigure${NC}    Edit bot token / channel / port
  ${GREEN}--backup${NC}         Backup database + config to ./backups/
  ${GREEN}--restore${NC}        Restore from a previous backup
  ${GREEN}--health${NC}         Check the aiohttp /health endpoint
  ${GREEN}--remove${NC}         Remove only the systemd service
  ${GREEN}--uninstall${NC}      Full uninstall (service + venv + logs + db)
  ${GREEN}-h, --help${NC}       Show this help message

${BOLD}No option${NC} -> interactive menu.

${BOLD}Supported platforms:${NC} SoundCloud, Spotify, YouTube, Pinterest,
                            Instagram, TikTok, Twitter (X)
${BOLD}Spotify mode:${NC}      spotapi (public, NO API keys needed)
EOF
}

# ----------------------------------------------------------------------------
#  Interactive menu
# ----------------------------------------------------------------------------
show_menu() {
    clear
    echo -e "${BOLD}${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║       Aurora Telegram Downloader Bot - Manager            ║"
    echo "║       SoundCloud | Spotify | YouTube | Pinterest |          ║"
    echo "║       Instagram | TikTok | Twitter (X)                       ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo -e "  Project:  ${PROJECT_DIR}"
    if [[ -f "$CONFIG_FILE" ]]; then
        local svc_kind="system"
        [[ "$USER_SERVICE" == "true" ]] && svc_kind="user"
        echo -e "  Service:  ${GREEN}${SERVICE_NAME}${NC} (${svc_kind})"
    else
        echo -e "  Service:  ${YELLOW}not configured${NC}"
    fi
    if [[ -f "$DB_PATH" ]]; then
        echo -e "  Database: ${GREEN}$(du -h "$DB_PATH" | cut -f1)${NC}"
    fi
    echo ""
    echo -e "  ${GREEN}1)${NC}  Install / Setup ${YELLOW}(first time)${NC}"
    echo -e "  ${GREEN}2)${NC}  Update Code & Dependencies"
    echo -e "  ${GREEN}3)${NC}  Restart Service"
    echo -e "  ${GREEN}4)${NC}  Stop Service"
    echo -e "  ${GREEN}5)${NC}  Service Status"
    echo -e "  ${GREEN}6)${NC}  View Logs ${YELLOW}(live)${NC}"
    echo -e "  ${GREEN}7)${NC}  Reconfigure ${YELLOW}(token / channel / port)${NC}"
    echo -e "  ${GREEN}8)${NC}  Backup Database & Config"
    echo -e "  ${GREEN}9)${NC}  Restore from Backup"
    echo -e "  ${GREEN}10)${NC} Health Check"
    echo -e "  ${GREEN}11)${NC} Remove Service"
    echo -e "  ${RED}12)${NC} ${RED}Full Uninstall${NC} ${YELLOW}(service + venv + logs + db)${NC}"
    echo -e "  ${GREEN}0)${NC}  Exit"
    echo ""
    read -rp "Choose an option [0-12]: " choice

    case "$choice" in
        1)  do_install ;;
        2)  do_update ;;
        3)  do_restart ;;
        4)  do_stop ;;
        5)  do_status ;;
        6)  do_logs ;;
        7)  do_reconfigure ;;
        8)  do_backup ;;
        9)  do_restore ;;
        10) do_health ;;
        11) do_remove_service ;;
        12) do_full_uninstall ;;
        0)  echo -e "${GREEN}Goodbye!${NC}"; exit 0 ;;
        *)  err "Invalid option"; sleep 1 ;;
    esac
}

# ----------------------------------------------------------------------------
#  CLI argument handling
# ----------------------------------------------------------------------------
if [[ $# -gt 0 ]]; then
    case "$1" in
        --install)     do_install ;;
        --update)      do_update ;;
        --restart)     do_restart ;;
        --stop)        do_stop ;;
        --status)      do_status ;;
        --logs)        do_logs ;;
        --reconfigure) do_reconfigure ;;
        --backup)      do_backup ;;
        --restore)     do_restore ;;
        --health)      do_health ;;
        --remove)      do_remove_service ;;
        --uninstall)   do_full_uninstall ;;
        -h|--help)     do_help ;;
        *)             err "Unknown option: $1"; do_help; exit 1 ;;
    esac
    exit 0
fi

# No arguments -> interactive loop
while true; do
    show_menu
done
